### ISSUE TITLE
Plugin breaks if items are not in order after certain manipulation of plugin

### ISSUE THREAD

**Issue by nissiongot** [pablo67340/GUIShop#100]
To Recreate: When the default configs are generated, in menu.yml delete the entire page1 section, then gs reload in game. Now, in the page0 section, remove a few keys from the last slot sections (in my case i did from 49-53). Reload using gs reload in game. When you do /shop menu still opens. However, now if you do /gs edit and remove a few of the slots from one of the rows above, and then close the editor, and you do /shop an internal error occurs, and this is because the slots that were removed in /gs edit are not there. If you fill them up with materials from config manually, and gs reload, this will go away. This is a bug because when the default configs are generated and you remove the slots using gs edit from anywhere in the middle, it doesnt produce this bug.

**Comment by pablo67340** [comment]
Are you using 9.0.6?

**Comment by nissiongot** [comment]
Yes I am 9.0.6

**Comment by pablo67340** [comment]
This has been fixed in 9.1.2.

Thanks for the report!
