### ISSUE TITLE
Items stack past their max stack size

### ISSUE THREAD

**Issue by PancakeCatsss** [pablo67340/GUIShop#107]
Pretty simple if i add something like a dragon egg to the shop for people to buy they can buy 64 of them but they are all stacked, please check the max stack size of an item before giving it to the player as this allows for op items such as 64 totems etc.

**Comment by Skyslycer** [comment]
Will fix! Thank you for the repoort.

**Comment by Skyslycer** [comment]
Fixed in 9.1.4, when Bryce merges and releases it's fixed.
