### ISSUE TITLE
guishop not working

### ISSUE THREAD

**Issue by sheet315** [pablo67340/GUIShop#123]
Whenever I run /shop, it says that the command doesnt exist, and if I use /gs in console I get this error:

27.12 10:49:17 [Server] Server thread/[WARN] [Minecraft/]: Unexpected exception while parsing console command "gs"
27.12 10:49:17 [Server] [INFO] org.bukkit.command.CommandException: Unhandled exception executing command 'gs' in plugin GUIShop v8.5
27.12 10:49:17 [Server] [INFO] at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[arclight:arclight-1.16.5-1.0.24-551ec3ff] {re:classloading}
27.12 10:49:17 [Server] [INFO] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[arclight:arclight-1.16.5-1.0.24-551ec3ff] {re:classloading}
27.12 10:49:17 [Server] [INFO] at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServerMixin.java:761) ~[arclight:arclight-1.16.5-1.0.24-551ec3ff] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftServerMixin,pl:mixin:A,pl:arclight_implementer:switch,pl:arclight_implementer:A}
27.12 10:49:17 [Server] [INFO] at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchServerCommand(CraftServerMixin.java:746) ~[arclight:arclight-1.16.5-1.0.24-551ec3ff] {re:mixin,re:classloading,pl:mixin:APP:mixins.arclight.bukkit.json:CraftServerMixin,pl:mixin:A,pl:arclight_implementer:switch,pl:arclight_implementer:A}
27.12 10:49:17 [Server] [INFO] at net.minecraft.server.dedicated.DedicatedServer.redirect$bbe000$arclight$serverCommandEvent(DedicatedServerMixin.java:655) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:A}
27.12 10:49:17 [Server] [INFO] at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServerMixin.java:312) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:A}
27.12 10:49:17 [Server] [INFO] at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServerMixin.java:292) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.dedicated.DedicatedServerMixin,pl:mixin:A}
27.12 10:49:20 [Server] [INFO] at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServerMixin.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
27.12 10:49:20 [Server] [INFO] at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServerMixin.java:1917) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
27.12 10:49:20 [Server] [INFO] at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServerMixin.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.arclight.core.json:server.MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
27.12 10:49:20 [Server] [INFO] at java.lang.Thread.run(Thread.java:829) [?:?] {}
27.12 10:49:20 [Server] [INFO] Caused by: java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_16_R3.command.ColouredConsoleSender cannot be cast to class org.bukkit.entity.Player (org.bukkit.craftbukkit.v1_16_R3.command.ColouredConsoleSender and org.bukkit.entity.Player are in unnamed module of loader cpw.mods.modlauncher.TransformingClassLoader @b950f82)
27.12 10:49:20 [Server] [INFO] at com.pablo67340.guishop.commands.GuishopCommand.onCommand(GuishopCommand.java:58) ~[?:?] {re:classloading,re:classloading,re:classloading,re:classloading,re:classloading}
27.12 10:49:20 [Server] [INFO] at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[arclight:arclight-1.16.5-1.0.24-551ec3ff] {re:classloading}
27.12 10:49:20 [Server] [INFO] ... 10 more

Im running java 11 btw

EDIT: I cannot change my java version as I am using Arclight, which requires java 11 at max. I use guishop v6.3.4 since that one says it uses java 11 and has 1.16.5 support.

**Comment by pablo67340** [comment]
Add my Discord: Bryce#0001

I can compile a version for you that is using Java 11. I am thinking of releasing multiple versions of GUIShop to fit the needs of people using different Java versions all together. I am noticing most people are not using Java 18 yet, and GUIShop isn't even using new Java 18 features yet, so I don't really see a reason (except for spigot using Java 18) to be compiling on Java 18 as of yet.

**Comment by pablo67340** [comment]
We might also have to adapt GUIShop to work with ArcLight. I am noticing in your error that it is trying to cast org.bukkit.craftbukkit.v1_16_R3.command.ColouredConsoleSender cannot be cast to class org.bukkit.entity.Player

ColouredConsoleSender (as far as I can tell, was never in spigot? I could be wrong though). I believe this could be something unique to ArcLight. If I am correct, and this is the case, GUIShop would have to be recompiled against ArcLight in order to work all together.

**Comment by sheet315** [comment]
Alright, my discord is Indestinate #2717
