### ISSUE TITLE
Probleme pour vendre

### ISSUE THREAD

**Issue by anthonyfakir** [pablo67340/GUIShop#16]
Bonjour , j'ai le probleme avec le plugins GUIShop ! 
je peux acheter mais je peux pas vendre .
que faire ?

**Comment by totemo** [comment]
@anthonyfakir  Les joueurs doivent utiliser /sell pour vendre des objets.

S'il vous plaît excusez mon Ffrançais. J'utilise Google Traduction.

Vous devrez peut-être accorder aux joueurs la permission de guishop.sell.
