### ISSUE TITLE
Error on shops with more than one page

### ISSUE THREAD

**Issue by kmckinney7** [pablo67340/GUIShop#18]
On shops with more than one page like "Blocks" in the default setup, the items on the first page can be just placed in inventory without purchase. An error occurs that allows this to happen.  Attached are screenshots of the behavior, the error, and the config.yml and shops.yml (with .txt only to load to the webpage). Spigotmc-1.12.2-R0.1.jar on Java 8 server.
![shop1](https://user-images.githubusercontent.com/16260940/35774215-f64063d2-0936-11e8-8e70-6300d2fe6681.PNG)
![shop2](https://user-images.githubusercontent.com/16260940/35774216-fc820f48-0936-11e8-8df9-e2a858fc645a.PNG)
![shop3](https://user-images.githubusercontent.com/16260940/35774218-01508bb2-0937-11e8-88e6-01e5807544fe.PNG)
![shop4](https://user-images.githubusercontent.com/16260940/35774221-0418fc44-0937-11e8-8c5a-c4f8c4147e12.PNG)
![shop5](https://user-images.githubusercontent.com/16260940/35774222-08609366-0937-11e8-8d9a-0e4103c81cee.PNG)
[config.txt](https://github.com/pablo67340/GUIShop/files/1692456/config.txt)
[shops.txt](https://github.com/pablo67340/GUIShop/files/1692457/shops.txt)

**Comment by pablo67340** [comment]
Can you go ahead and update to the latest version and let me know if this bug is still happening?

**Comment by pablo67340** [comment]
Closed.
