### ISSUE TITLE
Reserve Support

### ISSUE THREAD

**Issue by creatorfromhell** [pablo67340/GUIShop#20]
I am the developer of the plugin Reserve, a modern economy API with modern economy features in mind. I'm currently looking for developers to add support for it.

Link: https://www.spigotmc.org/resources/reserve.50739/

Thank you,
   creatorfromhell

**Comment by pablo67340** [comment]
Closed. Currently not looking to support any other economy API aside from Vault.

**Comment by creatorfromhell** [comment]
I would be interested in hearing the reasoning behind this.
