### ISSUE TITLE
1.13?

### ISSUE THREAD

**Issue by xTreMeDani** [pablo67340/GUIShop#26]
hello good, I would like to know if you plan to update for 1.13, just came to ask that, regards

**Comment by xTreMeDani** [comment]
Would you be so kind to give me an answer as to whether you will update the plugin for 1.13 or 1.13.x (when it comes out) ??

Please?

**Comment by TechieBlort** [comment]
His reply on this a while back: 

> I know many of you guys have been waiting for a 1.13 release. The main reason I didn't update GUIShop right away was due to the fact of 1.13 being in developmental faze. It was clear that 1.13 distro's were not meant for production, however many of you chose to use it anyways. If I had updated GUIShop right away, I would've had to frequently update it to keep up with the 1.13 patches, which I simply have no time for (especially when its a free plugin). I planned on waiting for a more stable release, and the rate at which spigot is updated has cooled down. Since then, 1.13.1 has come out, and it's looking much more stable. I plan on working on an update to work with 1.13.1 and beyond. This will take some time as a ton of the components GUIShop uses were changed, and need to be fixed. Hang in there!

**Comment by pablo67340** [comment]
Update:
https://www.spigotmc.org/resources/guishop.2451/
