### ISSUE TITLE
6.5 & 6.5.3a Farming Breaks Shop.

### ISSUE THREAD

**Issue by KennethRhodes8213** [pablo67340/GUIShop#29]
7.0 is broken so not sure if you fixed it but I wanted to point out that when you press on the farming button then go back and press it again you can just drag all the items to your inventory in the main section of the shop. I'd really love to see this plugin working because it seems like it has such good potential.

**Comment by pablo67340** [comment]
Ill look into the issue over the weekend. Thanks for your report.
