### ISSUE TITLE
Using GUIShop as a dependency

### ISSUE THREAD

**Issue by Solmex72** [pablo67340/GUIShop#30]
Hello, this isn't an issue, but I was wondering if I could get some advice.

I have a plugin called NavyCraft that has vehicles that move blocks, like Movecraft, and I was wondering how I could detect GUIShop chests on board of the vehicle, then move them as the vehicle moves.

**Comment by pablo67340** [comment]
GUIShop would have nothing to do with the feature you are requesting. NavyCraft would be in charge of this, so it would need to be added to their plugin. Lastly, GUIShop doesn't have chests?
