### ISSUE TITLE
Buying a command once expired

### ISSUE THREAD

**Issue by Kylerchrdsn** [pablo67340/GUIShop#31]
Looks like there is a bug that prevents you from buying a command again once it expires. I've fixed this in a forked version of the code and I will likely make a pull request with the fix sometime soon. If you fix it before I get around to making the pull request, all the better.

**Comment by pablo67340** [comment]
If you could make a pull request, that would be great! I'd be able to review and approve it asap.

**Comment by pablo67340** [comment]
Approved, thank you so much for your contribution! I'll make a release on spigot now.
