### ISSUE TITLE
Issue with Enchanted Books

### ISSUE THREAD

**Issue by 2000game** [pablo67340/GUIShop#41]
When I try to sell Enchanted Books, the Books dont actually have the enchantment. Even after I bought them. I also tried using them in an anvil but that didnt work out either. When Ive bought the sword or the axe Im ablte to see the enchantment. Im on 1.15.2 Spigot. 
Enchanted:
 '0':
    type: SHOP
    id: ENCHANTED_BOOK
    buy-price: 6000.0
    enchantments: EFFICIENCY:1
 '1':
    type: SHOP
    id: DIAMOND_SWORD
    buy-price: 100
    shop-lore: 
    - '&aThis is the sword of unbreakingness'
    shop-name: '&bSword of the &0Unbreaking'
    enchantments: DURABILITY:1
    buy-lore: 
    - '&aPurchased by {PLAYER_NAME} for {BUY_PRICE}'
 '2':
    type: SHOP
    id: STICK
    buy-price: 6000.0
    enchantments: EFFICIENCY:1

**Comment by GBadlon** [comment]
For further bug tracing, I have tried this in 1.15.2,1.14.4 and 1.14

I have tried, adding the book with the `guishop edit` command and I have also tried adding it in the config, neither did anything but give a book that has an enchanting glow but nothing more.

**Comment by phortx** [comment]
Ccn reproduce with 1.15.2

**Comment by phortx** [comment]
I think the issue is that Bukkit differs between Entchantments and StoredEntchantments.

For the books there should be a `stored-entchantments` option for the shops.yml, I think.

**Comment by pablo67340** [comment]
This will be implemented for 8.2
