### ISSUE TITLE
Typo in shops.yml

### ISSUE THREAD

**Issue by GBadlon** [pablo67340/GUIShop#42]
I noticed this while trying to learn more about what each option meant, what it was used for and things like that. Again, this is low on the priority list as it's just shown as a guide and it's commented out but I thought I should mention it.

{CURRENCY_SYMBOL} gets generated as {CURRENY_SYMBOL} at least that is what 2 tests that I did showed me.

**Comment by A248** [comment]
At least `{CURRENCY_SYMBOL}` is used in the actual source code, even if the config.yml has a typo.

**Comment by pablo67340** [comment]
Fixed
