### ISSUE TITLE
Problems Cloning and Building from Source

### ISSUE THREAD

**Issue by A248** [pablo67340/GUIShop#43]
I'm very glad GuiShop is open-source, because it encourages collaboration to improve the plugin and makes adding custom features easy.

That said, there are a few problems my IDE and maven report after cloning and building the source:

1. The section sign ('§') is replaced with a broken character, '�', when I initially clone the repository. However, if one conducts a find and replace for all '�' with '§', git reports a diff and wants the changes to be committed. *Note that the characters are not changed when forking but when cloning the repo.*
2. Because the `.classpath` references libraries on your personal computer (e.g. "C:/Users/Bryce/Desktop/1.15.2/plugins/Vault.jar") the project initially fails to build. This can be solved by removing the .classpath references, which are unnecessary because maven already resolves all dependencies. However, again it results in a git diff.
3. There are 2 IDE errors related to the same construct. There's a comment describing the lines: "Use for comment injection method for forward & backward compat". I'm not sure what this means or how to solve it, but I do know that it makes Eclipse angry. (Quantity.java:110 and Shop.java:234)

I can make a PR to fix problem 1 and problem 2, but I don't know what to do for problem 3.

**Comment by pablo67340** [comment]
I will look into these issues for 7.3.9's release. Thanks for the report!
