### ISSUE TITLE
An arrow appeared in one of my shops

### ISSUE THREAD

**Issue by Federe76** [pablo67340/GUIShop#46]
![image](https://user-images.githubusercontent.com/62208477/77108490-0d5e0b00-6a01-11ea-9f28-a59be80c4d67.png)

![image](https://user-images.githubusercontent.com/62208477/77108639-531ad380-6a01-11ea-8cc8-cbf40c9804d0.png)

![image](https://user-images.githubusercontent.com/62208477/77108088-65e0d880-6a00-11ea-937e-a7680e46c118.png)

First image working as intended. I wanted to add bamboo to that shop, so I rearranged the items, but when I did, that arrow showed up. I looked inside the shops file for the word arrow but it's nowhere to be found, not even in other shops. It doesn't do anything, it's like a dummy item, no message in chat, no error in console.

**Comment by pablo67340** [comment]
Ah, this is a simple fix I can implement in a future version. This is being caused by an item being in the last slot on the second last row, when instead, it needs to check if an item is in the first slot of the last row.

**Comment by Federe76** [comment]
Great. As I said, it doesn't break anything functionally (at least in my case), so there is no rush.
Thanks.
