### ISSUE TITLE
Feature Request: Show Sell-Price in Sell GUI

### ISSUE THREAD

**Issue by A248** [pablo67340/GUIShop#54]
This feature was suggested by *Coco* on the Discord. It will look like this:
![Feature Preview](https://cdn.discordapp.com/attachments/464333963637293057/697409061968412702/2020-04-08_13.34.16.png)

The price will of course be updated whenever a user adds an item to the GUI. The item display name will be set to reflect the price.

**Comment by A248** [comment]
Also, we need to remember to change the name *back* if a user withdraws the item from the sell GUI.

**Comment by A248** [comment]
For now I won't be working on this feature since I have too many other things to do at the moment, so I'll let you know what I've found out.

The spigot docs are notably unclear in general but in particular with regards to how events are triggered. Sometimes method calls trigger events – `player.teleport(Location)` triggers the PlayerTeleportEvent and `Entity.setHealth(0)` a death event. Also, some events lead to others: the PlayerTeleportEvent comes before the PlayerChangedWorldEvent.

With regards to GUIs, it isn't clear whether the InventoryDragEvent leads to the InventoryClickEvent. GUIShop uses the library IF, which doesn't listen to the InventoryDragEvent, which suggests it isn't required. However, the [SkRayFall source](https://github.com/eyesniper2/skRayFall/blob/master/src/main/java/net/rayfall/eyesniper2/skrayfall/general/events/StoreListener.java), which implements a `StoreEvent`, clearly listens to the InventoryDragEvent, implying it is a possible way for players to add items to a GUI.

If this feature request is to be implemented, we have to be sure of these details in order to determine the exact moments and causes why an item is added to the GUI. InventoryClickEvent's InventoryAction has quite a few values.

I may just be less knowledgeable on this topic, so anyone is free to cast doubt on my conjectures and assumptions. If you discover anything let me know; I'd like to know.

**Comment by pablo67340** [comment]
The only thing I'd suggest is using the InventoryInteractEvent. Perhaps check if the player clicked the player GUI while /sell is open. If so, delete the clicked itemstack, duplicate it with the sell lore, and add it to the first available slot in the slel gui

**Comment by A248** [comment]
I decided I won't be working on this feature request anytime in the foreseeable future. If anyone wants to make a PR feel free.
