### ISSUE TITLE
Possible improvements

### ISSUE THREAD

**Issue by Spiderjockey02** [pablo67340/GUIShop#57]
1.) Allow multi-line 'Desc' in config.yml
2.) Each shop category to have an option for row size (max 6)
3.) Allow the 'Back' button to be placed anywhere in the bottom row (preferable in the center)
4.) A more user friendly 'buying stage' so instead of clicking 1,2,4,8,16,32,64 to set the number of items to buy you could have a GUI that instead of setting to that number you add or minus from your starting number. Example:
![unknown](https://user-images.githubusercontent.com/55885015/79329914-83766480-7f10-11ea-9411-b0e0da9e304c.png)

**Comment by pablo67340** [comment]
Thank you for these suggestions. We'll see if we can factor any of these in for future updates.
