### ISSUE TITLE
Sell Issue

### ISSUE THREAD

**Issue by Skiller9090** [pablo67340/GUIShop#66]
If you have two items being sold one with COMMAND and the other with SHOP and they both have the id of the same item. When COMMAND is registered with either sell false or not even with a sell price you cant sell the item with the SHOP type with correct sell price setup.
This is a new bug when i transferred from 7.3.9 to 8.0.0
please fix soon

**Comment by pablo67340** [comment]
What server version are you using?

**Comment by Skiller9090** [comment]
1.15

**Comment by pablo67340** [comment]
I will be looking into this for the next update. Thanks!

**Comment by pablo67340** [comment]
Issue Closed. Fixed.
