### ISSUE TITLE
When the shops.yml was edited wrongly,it will clear the player's bag!!

### ISSUE THREAD

**Issue by mrjesen** [pablo67340/GUIShop#68]
When the shops.yml was edited wrongly,and then the player open the GUI by "/buy", it will clear the player's bag,its really a bug!!!!!!!!!!!!!!!!!

**Comment by pablo67340** [comment]
What do you mean by clears their bag? Are you using this on a modded server?

**Comment by mrjesen** [comment]
no,not a modded server,it is a paper server.
"clears their bag" = "made their invetory empty"

**Comment by pablo67340** [comment]
What server version are you using?

**Comment by mrjesen** [comment]
1.15.2

**Comment by Skyslycer** [comment]
Ohh i had this thing too i remember. I might look into this tmrw

**Comment by pablo67340** [comment]
Issue Closed. Resolved many commits ago!
