### ISSUE TITLE
Blocks Menu is blank

### ISSUE THREAD

**Issue by Flare183** [pablo67340/GUIShop#73]
I'm using the prerelease of GUIShop, and I've noticed that the Blocks Menu has all blank items in them. Is there anyway you can fix this? I've checked the config and it looks fine.
![Screenshot_2020-07-16_17-02-37](https://user-images.githubusercontent.com/4323/87722556-4d05eb00-c786-11ea-81ff-c387b2535dc6.png)

**Comment by A248** [comment]
That usually means one of the items in the Blocks shop has an invalid material.

**Comment by pablo67340** [comment]
XMaterial has been updated to support every item up to 1.16.3. This should fix the problem you are having.
