### ISSUE TITLE
gui shop wont load

### ISSUE THREAD

**Issue by groblerawr** [pablo67340/GUIShop#74]
![ripstick](https://user-images.githubusercontent.com/1789516/87894905-0debca00-ca12-11ea-93c3-e74d7e1cb6b8.png)

**Comment by A248** [comment]
Use the code from the master branch, or join the discord if you don't know how to compile source.

**Comment by ShayBox** [comment]
Master branch doesn't fix it

**Comment by A248** [comment]
It was, here. The NoSuchMethodError is caught:
https://github.com/pablo67340/GUIShop/pull/69/commits/6d47120ce8a4a6753695ddb5b0e9e24947c0e345

Other users are not having an issue with this using the code from the master branch. If you have a different problem join the discord to get support.

**Comment by pablo67340** [comment]
You are not using Spigot, instead you are using Core bukkit. Please update to Spigot and the plugin will work fine.

**Comment by ShayBox** [comment]
Bukkit isn't available to build for 1.16,thats not possible.
