### ISSUE TITLE
shop will not open 

### ISSUE THREAD

**Issue by artimoose** [pablo67340/GUIShop#76]
Error occurred while enabling GUIShop v8.0 (Is it up to date?)
java.lang.NullPointerException: null
        at com.pablo67340.guishop.listenable.Shop.loadShop(Shop.java:242) ~[?:?]
        at com.pablo67340.guishop.listenable.Shop.loadItems(Shop.java:192) ~[?:?]
        at com.pablo67340.guishop.listenable.Menu.itemWarmup(Menu.java:49) ~[?:?]
        at com.pablo67340.guishop.Main.loadShopDefs(Main.java:188) ~[?:?]
        at com.pablo67340.guishop.Main.onEnable(Main.java:149) ~[?:?]
this is the error I get

**Comment by artimoose** [comment]
[17:37:48 ERROR]: Error occurred while enabling GUIShop v8.0 (Is it up to date?)
java.lang.NullPointerException: null
        at com.pablo67340.guishop.listenable.Shop.loadShop(Shop.java:242) ~[?:?]
        at com.pablo67340.guishop.listenable.Shop.loadItems(Shop.java:192) ~[?:?]
        at com.pablo67340.guishop.listenable.Menu.itemWarmup(Menu.java:49) ~[?:?]
        at com.pablo67340.guishop.Main.loadShopDefs(Main.java:188) ~[?:?]
        at com.pablo67340.guishop.Main.onEnable(Main.java:149) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[Spigot.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [Spigot.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [Spigot.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [Spigot.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [Spigot.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [Spigot.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [Spigot.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [Spigot.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [Spigot.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [Spigot.jar:git-Spigot-dcd1643-e60fc34]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]

full error from console

**Comment by artimoose** [comment]
##################################################
##                                              ##
##  _____ _    _ _____  _____ _                 ##
## / ____| |  | |_   _|/ ____| |                ##
##| |  __| |  | | | | | (___ | |__   ___  _ __  ##
##| | |_ | |  | | | |  \___ \| '_ \ / _ \| '_ \ ##
##| |__| | |__| |_| |_ ____) | | | | (_) | |_) |##
## \_____|\____/|_____|_____/|_| |_|\___/| .__/ ##
##                                       | |    ##
##                                       |_|    ##
##################################################



##################################################
#             Looking for Item Names?            #
##################################################
#           https://tinyurl.com/okqdcvo          #
##################################################

## Tag in chat before text in chat from shop. e.g [GUIShop] Purchase Successful.
prefix: '[&cGUIShop&f]'

## Command used to open shop, DON'T PUT A /
buy-commands: 
    - 'buy'
    - 'shop'

## Command to open sell inventory, DON'T PUT A /
sell-commands:
    - 'sell'

## Register the commands
## if set to false, you must do '/guishopuser buy' instead of '/buy'
register-commands: true

############ Language settings ###############

#No permission message
no-permission: '&cNo Permission!'

#Disabled world message
disabled-world: '&cYou cannot use the shop from this world!'

#Use the escape key to close the shop instead of the back button.
escape-only: true

#Rightclick an item in the shop to open an alternate sell GUI
alternate-sell-enable: false

#The message for the amount you lose, E.G Cost, Or Price
cost: '&7Price'

#The message for the amount you get back AKA. Sell or Returned
return: '&7Sell'

#The 1st line of the message on shop items
line1: '&8To sell, click the item in your inv.'

#The 2nd line of the message on shop items
line2: '&6Must be the same quantity!'

#The 3rd line of the message on shop items
line3: 'Click to buy item of quantity'

#The 4th line of the message on shop items
line4: 'Shift+Click to buy 1 item'

#The text back button in the shops
back: '&cBack'

#The item the back button will be!
back-button-item: 'RED_STAINED_GLASS_PANE'

#The messaged displayed before the item amount.

purchased: '&fA purchase was made, and &c$'

## The second message displayed when you purchase an item.

## E.G 54$ Taken from your account.
taken: '&f was taken from your account.'

##  The words displayed before the amount needed.
not-enough-pre: '&fYou need &c$'

## The words displayed AFTER the amount needed.
not-enough-post: '&f to purchase this!'

## Text displayed before item name.
sold: '&fYour items were sold, and &a$'

##Second message when buying, Words AFTER the amount
## E.G 54$ "Added to your account"
added: '&f was added to your account.'

#When something magical goes wrong?
something-wrong: '&fSomething went wrong, contact an admin.'

#Message displayed when a player tries to sell blocks not matching the quantity.
in-stacks: '&fPlease sell in stacks of &c'

#Message when a player cannot sell a certain item.
#{count} can be used to display the amount of non sellable, returned items.
cant-sell: '&f({count}) item(s) failed to sell and have been returned to your inventory.'

#Message when a player cannot buy a certain item.
cant-buy: '&fSorry, you are not able to buy that item.'

#When a player has a full inventory
full-inventory: '&cPlease empty your inventory!'

#The currency symbol
currency: '$'

#The suffix after the currency. E.G Dollars. Yen, etc.
currency-suffix: ''

#The title of a sign that players can click to open shop
sign-title: '[&cGUIShop&f]'

#Do want players to be able to access the shop ONLY using the sign? 
signs-only: false

signs-only-message: '&cYou can only access the shop by clicking a [&cGUIShop&f] sign!'

#Menu row count
menu-rows: 3

#Enable sound on purchase
enable-sound: true

#Purchase sound effect (You can find them here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html)
purchase-sound: 'ENTITY_PLAYER_LEVELUP'

#Enable in-game creator.
ingame-config: true

#Enable dynamic pricing
dynamic-pricing: false

#Enable DEBUG mode
debug-mode: true

#The overall shop menu title
menu-title: "Menu"

#The title of a specific shop inventory
shop-title: "Menu &f> &r{shopname}"

#The title of the sell inventory
sell-title: "Menu &f> &rSell"

#The title of the quantity inventory.
qty-title: "&4Select Amount"

#The title of the alternate sell GUI, if enabled
alt-sell-title: "Menu &f> &rSell"

access-to: "&aAccess to Commands:"

buy-lore: "&fBuy: &c{amount}"

sell-lore: "&fSell: &c{amount}"

free-lore: "&fBuy: &aFREE"

cannot-buy: "&cCannot Purchase"

cannot-sell: "&cCannot Sell"

forward-page-button-name: "&rNext page"

backward-page-button-name: "&rLast page"

#Used in the alternate sell GUI
alt-sell-indicator-material: 'GOLD_INGOT'

alt-sell-add-material: 'GREEN_STAINED_GLASS_PANE'
alt-sell-remove-material: 'RED_STAINED_GLASS_PANE'

alt-sell-quantity-1: 1
alt-sell-quantity-2: 10
alt-sell-quantity-3: 64

alt-sell-confirm-material: 'EMERALD_BLOCK'
alt-sell-cancel-material: 'REDSTONE_BLOCK'

alt-sell-confirm-name: '&a&lConfirm'
alt-sell-cancel-name: '&c&lCancel'

alt-sell-not-enough: '&cYou do not have {amount} such items to sell.'

DisabledWorlds:
    -'Test'

## Items to disable quantity stacking. 
## This will force these items to only have
## a quantity of 1. Good for swords, armor, etc.
##
## This is an item SEARCH. Meaning it is not the full item name.
## E.G CHESTPLATE blocks ALL chestplates because all items contain
## the word CHESTPLATE.
disabled-qty-items:
    - "CHESTPLATE"
    - "LEGGINGS"
    - "BOOTS"
    - "HELMET"
    - "BOW"
    - "FISHING_ROD"
    - "SHEARS"
    - "NAME_TAG"
    - "SWORD"
    - "AXE"
    - "PICKAXE"
    - "SHOVEL"
    - "SPADE"
    - "HOE"
    - "LEAD"
    - "LEASH"
    - "HORSE_ARMOR"
    - "SADDLE"
    - "BARDING"

##Menu Items
Rows: 3

menu-items:
  Pane0:
    Type: 'DUMMY'
    Item: 'BLUE_STAINED_GLASS_PANE'
  Pane1:
    Type: 'DUMMY'
    Item: 'RED_STAINED_GLASS_PANE'
  Pane2:
    Type: 'DUMMY'
    Item: 'BLUE_STAINED_GLASS_PANE'
  Pane3:
    Type: 'DUMMY'
    Item: 'RED_STAINED_GLASS_PANE'
  Pane4:
    Type: 'DUMMY'
    Item: 'BLUE_STAINED_GLASS_PANE'
  Pane5:
    Type: 'DUMMY'
    Item: 'RED_STAINED_GLASS_PANE'
  Pane6:
    Type: 'DUMMY'
    Item: 'BLUE_STAINED_GLASS_PANE'
  Pane7:
    Type: 'DUMMY'
    Item: 'RED_STAINED_GLASS_PANE'
  PaneCornerRight:
    Type: 'DUMMY'
    Item: 'BLUE_STAINED_GLASS_PANE'
  Pane8:
    Type: 'DUMMY'
    Item: 'RED_STAINED_GLASS_PANE'
  Raiding:
    Type: 'SHOP'
    Enabled: true
    Item: 'TNT'
    Desc: '&8(&fBlow them up!&8)'
    Name: '&4Raiding'
  Ores:
    Type: 'SHOP'
    Enabled: true
    Item: 'EMERALD'
    Desc: '&8(&fOres&8)'
    Name: '&aOres'
  FarmingDrops:
    Type: 'SHOP'
    Enabled: true
    Item: 'WHEAT_SEEDS'
    Desc: '&8(&fFarming&8)'
    Name: '&eFarming/Drops'
  Brewing/Drops:
    Type: 'SHOP'
    Enabled: true
    Item: 'EXPERIENCE_BOTTLE'
    Desc: '&8(&fBrewing&8)'
    Name: '&2Brewing'
  Specialty:
    Type: 'SHOP'
    Enabled: true
    Item: 'DIAMOND_HELMET'
    Desc: '&8(&fSpecialty&8)'
    Name: '&bSpecialty'
  Spawners:
    Type: 'SHOP'
    Enabled: true
    Item: 'SPAWNER'
    Desc: '&8(&fSpawners&8)'
    Name: '&6Spawners'
  Blocks:
    Type: 'SHOP'
    Enabled: true
    Item: 'STONE'
    Desc: '&8(&fBlocks&8)'
    Name: '&6Blocks'
  Decoration:
    Type: 'SHOP'
    Enabled: true
    Item: 'GLASS'
    Desc: '&8(&fDecor&8)'
    Name: '&6Decorations'
  PaneCornerBottomLeft:
    Type: 'DUMMY'
    Item: 'BLUE_STAINED_GLASS_PANE'
  Pane10:
    Type: 'DUMMY'
    Item: 'RED_STAINED_GLASS_PANE'
  Pane11:
    Type: 'DUMMY'
    Item: 'BLUE_STAINED_GLASS_PANE'
  Pane12:
    Type: 'DUMMY'
    Item: 'RED_STAINED_GLASS_PANE'
  Pane13:
    Type: 'DUMMY'
    Item: 'BLUE_STAINED_GLASS_PANE'
  Pane14:
    Type: 'DUMMY'
    Item: 'RED_STAINED_GLASS_PANE'
  Pane15:
    Type: 'DUMMY'
    Item: 'BLUE_STAINED_GLASS_PANE'
  Pane16:
    Type: 'DUMMY'
    Item: 'RED_STAINED_GLASS_PANE'
  Pane17:
    Type: 'DUMMY'
    Item: 'BLUE_STAINED_GLASS_PANE'

 ################################
 ## Developed by pablo67340    ##
 ## If you need any support    ##
 ## https://discord.gg/v7D6pCm ##
 ################################

config.yml file

**Comment by artimoose** [comment]
# 
#                           Looking for Item Names?                       #
Raiding:
  '0':
    type: SHOP
    id: STONE_PRESSURE_PLATE
    buy-price: 25.0
  '1':
    type: SHOP
    id: STONE_SLAB
    buy-price: 50.0
  '2':
    type: SHOP
    id: REDSTONE_TORCH
    buy-price: 25.0
  '3':
    type: SHOP
    id: REDSTONE_BLOCK
    buy-price: 195.0
    sell-price: 10.0
  '4':
    type: SHOP
    id: COMPARATOR
    buy-price: 100.0
  '5':
    type: SHOP
    id: REPEATER
    buy-price: 85.0
  '6':
    type: SHOP
    id: REDSTONE
    buy-price: 16.25
    sell-price: 0.23
  '7':
    type: SHOP
    id: WATER_BUCKET
    buy-price: 500.0
  '8':
    type: SHOP
    id: LAVA_BUCKET
    buy-price: 500.0
  '9':
    type: SHOP
    id: STONE_BUTTON
    buy-price: 5.5
  '10':
    type: SHOP
    id: TNT
    buy-price: 81.25
    sell-price: 8.12
  '11':
    type: SHOP
    id: DISPENSER
    buy-price: 819.0
  '12':
    type: SHOP
    id: STICKY_PISTON
    buy-price: 325.0
  '13':
    type: SHOP
    id: PISTON
    buy-price: 195.0
  '14':
    type: SHOP
    id: GLOWSTONE
    buy-price: 20.0
    sell-price: 2.5
  '15':
    type: SHOP
    id: GLASS
    buy-price: 4.06
  '16':
    type: SHOP
    id: LADDER
    buy-price: 10.0
  '17':
    type: SHOP
    id: COBWEB
    buy-price: 40.0
  '18':
    type: SHOP
    id: SPONGE
    buy-price: 2000.0
  '19':
    type: SHOP
    id: LEVER
    buy-price: 20.0
  '20':
    type: SHOP
    id: OAK_TRAPDOOR
    buy-price: 50.0
  '21':
    type: SHOP
    id: ICE
    buy-price: 50.0
  '22':
    type: SHOP
    id: CREEPER_SPAWN_EGG
    buy-price: 250000.0
  '23':
    type: SHOP
    id: FLINT_AND_STEEL
    buy-price: 500.0
  '24':
    type: SHOP
    id: FISHING_ROD
    buy-price: 500.0
Ores:
  '0':
    type: SHOP
    id: EMERALD
    buy-price: 1150.0
    sell-price: 200.0
  '1':
    type: SHOP
    id: EMERALD_BLOCK
    buy-price: 8775.0
    sell-price: 1250.0
  '2':
    type: SHOP
    id: DIAMOND
    buy-price: 390.0
    sell-price: 100.0
  '3':
    type: SHOP
    id: DIAMOND_BLOCK
    buy-price: 3500.0
    sell-price: 800.0
  '4':
    type: SHOP
    id: IRON_INGOT
    buy-price: 130.0
    sell-price: 30.0
  '5':
    type: SHOP
    id: IRON_BLOCK
    buy-price: 1170.0
    sell-price: 270.0
  '6':
    type: SHOP
    id: GOLD_INGOT
    buy-price: 100.0
    sell-price: 50.0
  '7':
    type: SHOP
    id: GOLD_BLOCK
    buy-price: 1850.0
    sell-price: 450
  '8':
    type: SHOP
    id: COAL
    buy-price: 4.53
    sell-price: 0.47
  '9':
    type: SHOP
    id: COAL_BLOCK
    buy-price: 40.0
    sell-price: 4.0
  '10':
    type: SHOP
    id: LAPIS_LAZULI
    buy-price: 18.12
    sell-price: 1.25
  '11':
    type: SHOP
    id: LAPIS_BLOCK
    buy-price: 160.0
    sell-price: 9.0
FarmingDrops:
  '0':
    type: SHOP
    id: OAK_SAPLING
    buy-price: 5.0
  '1':
    type: SHOP
    id: SPRUCE_SAPLING
    buy-price: 5.0
  '2':
    type: SHOP
    id: BIRCH_SAPLING
    buy-price: 5.0
  '3':
    type: SHOP
    id: JUNGLE_SAPLING
    buy-price: 5.0
  '4':
    type: SHOP
    id: ACACIA_SAPLING
    buy-price: 5.0
  '5':
    type: SHOP
    id: DARK_OAK_SAPLING
    buy-price: 3.0
  '6':
    type: SHOP
    id: WHEAT_SEEDS
    buy-price: 2.19
  '7':
    type: SHOP
    id: PUMPKIN_SEEDS
    buy-price: 3.44
  '8':
    type: SHOP
    id: MELON_SEEDS
    buy-price: 3.44
  '9':
    type: SHOP
    id: SUGAR_CANE
    buy-price: 16.25
    sell-price: 3.12
  '10':
    type: SHOP
    id: CACTUS
    buy-price: 18.75
    sell-price: 1.88
  '11':
    type: SHOP
    id: MELON
    buy-price: 20.31
    sell-price: 3.14
  '12':
    type: SHOP
    id: PUMPKIN
    buy-price: 325.0
    sell-price: 2.65
  '13':
    type: SHOP
    id: WEHAT
    buy-price: 11.88
    sell-price: 6.25
  '14':
    type: SHOP
    id: APPLE
    buy-price: 25.0
    sell-price: 10.0
  '15':
    type: SHOP
    id: GOLDEN_APPLE
    buy-price: 1500.0
  '16':
    type: SHOP
    id: CAKE
    buy-price: 50.0
  '17':
    type: SHOP
    id: BREAD
    buy-price: 31.25
  '18':
    type: SHOP
    id: COOKIE
    buy-price: 5.94
  '19':
    type: SHOP
    id: RAW_BEEF
    buy-price: 9.38
    sell-price: 2.19
  '20':
    type: SHOP
    id: COOKED_BEEF
    buy-price: 11.88
    sell-price: 2.81
  '21':
    type: SHOP
    id: PORKCHOP
    buy-price: 10.0
    sell-price: 1.25
  '22':
    type: SHOP
    id: COOKED_PORKCHOP
    buy-price: 11.88
    sell-price: 1.88
  '23':
    type: SHOP
    id: CARROT
    buy-price: 25.0
    sell-price: 1.56
Brewing/Drops:
  '0':
    type: SHOP
    id: GHAST_TEAR
    buy-price: 97.5
    sell-price: 40.0
  '1':
    type: SHOP
    id: SPIDER_EYE
    buy-price: 130.0
    sell-price: 7.5
  '2':
    type: SHOP
    id: BREWING_STAND
    buy-price: 315.0
  '3':
    type: SHOP
    id: GOLDEN_CARROT
    buy-price: 73.12
  '4':
    type: SHOP
    id: GLOWSTONE_DUST
    buy-price: 5.0
    sell-price: 0.01
  '5':
    type: SHOP
    id: SUGAR
    buy-price: 5.0
  '6':
    type: SHOP
    id: SLIME_BALL
    buy-price: 200.0
    sell-price: 3.0
  '7':
    type: SHOP
    id: NETHER_WART
    buy-price: 16.25
    sell-price: 4.06
  '8':
    type: SHOP
    id: GLISTERING_MELON_SLICE
    buy-price: 38.72
  '9':
    type: SHOP
    id: GUNPOWEDER
    buy-price: 25.0
    sell-price: 4.38
  '10':
    type: SHOP
    id: ARROW
    buy-price: 6.25
    sell-price: 2.19
  '11':
    type: SHOP
    id: FEATHER
    buy-price: 8.12
    sell-price: 1.09
  '12':
    type: SHOP
    id: BLAZE_ROD
    buy-price: 62.5
    sell-price: 28.75
  '13':
    type: SHOP
    id: LILY_PAD
    buy-price: 20.0
  '14':
    type: SHOP
    id: ROTTEN_FLESH
    buy-price: 2.5
    sell-price: 1.09
  '15':
    type: SHOP
    id: STRING
    buy-price: 8.12
    sell-price: 1.88
  '16':
    type: SHOP
    id: LEATHER
    buy-price: 16.25
    sell-price: 5.62
  '17':
    type: SHOP
    id: ENDER_PEARL
    buy-price: 50.0
    sell-price: 25.0
  '18':
    type: SHOP
    id: BONE
    buy-price: 6.25
    sell-price: 0.5
Spawners:
  '0':
    type: SHOP
    id: SPAWNER
    buy-price: 390000.0
    shop-name: Creeper Spawner
    mobType: CREEPER
  '1':
    type: SHOP
    id: SPAWNER
    buy-price: 115000.0
    shop-name: Skeleton Spawner
    mobType: SKELETON
  '2':
    type: SHOP
    id: SPAWNER
    buy-price: 95000.0
    shop-name: Spider Spawner
    mobType: SPIDER
  '3':
    type: SHOP
    id: SPAWNER
    buy-price: 115000.0
    shop-name: Zombie Spawner
    mobType: ZOMBIE
  '4':
    type: SHOP
    id: SPAWNER
    buy-price: 1300000.0
    shop-name: Slime Spawner
    mobType: SLIME
  '5':
    type: SHOP
    id: SPAWNER
    buy-price: 4000000.0
    shop-name: Ghast Spawner
    mobType: GHAST
  '6':
    type: SHOP
    id: SPAWNER
    buy-price: 390000.0
    shop-name: Zombie Pigman Spawner
    mobType: ZOMBIE_PIGMAN
  '7':
    type: SHOP
    id: SPAWNER
    buy-price: 390000.0
    shop-name: Enderman Spawner
    mobType: ENDERMAN
  '8':
    type: SHOP
    id: SPAWNER
    buy-price: 90000.0
    shop-name: Cave Spider Spawner
    mobType: CAVE_SPIDER
  '9':
    type: SHOP
    id: SPAWNER
    buy-price: 2000000.0
    shop-name: Iron Golem Spawner
    mobType: IRON_GOLEM
  '10':
    type: SHOP
    id: SPAWNER
    buy-price: 390000.0
    shop-name: Blaze Spawner
    mobType: BLAZE
  '11':
    type: SHOP
    id: SPAWNER
    buy-price: 162500.0
    shop-name: Cow Spawner
    mobType: COW
  '12':
    type: SHOP
    id: SPAWNER
    buy-price: 95000.0
    shop-name: Sheep Spawner
    mobType: SHEEP
  '13':
    type: SHOP
    id: SPAWNER
    buy-price: 65000.0
    shop-name: Chicken Spawner
    mobType: CHICKEN
  '15':
    type: SHOP
    id: SPAWNER
    buy-price: 97500.0
    shop-name: Wolf Spawner
    mobType: WOLF
Blocks:
  '1':
    type: SHOP
    id: DIRT
    buy-price: 3.0
    sell-price: 0.69
  '2':
    type: SHOP
    id: OAK_WOOD
    buy-price: 8.12
    sell-price: 2.03
  '3':
    type: SHOP
    id: SPRUCE_WOOD
    buy-price: 8.12
    sell-price: 2.03
  '4':
    type: SHOP
    id: BIRCH_WOOD
    buy-price: 8.12
    sell-price: 2.03
  '5':
    type: SHOP
    id: JUNGLE_WOOD
    buy-price: 8.12
    sell-price: 2.03
  '6':
    type: SHOP
    id: ACACIA_WOOD
    buy-price: 8.12
    sell-price: 2.03
  '7':
    type: SHOP
    id: DARK_OAK_WOOD
    buy-price: 8.12
    sell-price: 2.03
  '8':
    type: SHOP
    id: PODZOL
    buy-price: 10.94
    sell-price: 3.75
  '9':
    type: SHOP
    id: MYCELIUM
    buy-price: 10.16
    sell-price: 3.75
  '10':
    type: SHOP
    id: STONE
    buy-price: 5.47
    sell-price: 1.48
  '11':
    type: SHOP
    id: COBBLESTONE
    buy-price: 4.06
    sell-price: 1.02
  '12':
    type: SHOP
    id: STONE_BRICKS
    buy-price: 6.56
  '13':
    type: SHOP
    id: MOSSY_STONE_BRICKS
    buy-price: 6.56
  '14':
    type: SHOP
    id: CRACKED_STONE_BRICKS
    buy-price: 6.56
  '15':
    type: SHOP
    id: CHISELED_STONE_BRICKS
    buy-price: 6.56
  '16':
    type: SHOP
    id: SANDSTONE
    buy-price: 12.19
  '17':
    type: SHOP
    id: CHISELED_SANDSTONE
    buy-price: 12.19
  '18':
    type: SHOP
    id: SMOOTH_SANDSTONE
    buy-price: 48.75
  '19':
    type: SHOP
    id: QUARTZ_BLOCK
    buy-price: 12.19
  '20':
    type: SHOP
    id: QUARTZ_BRICKS
    buy-price: 48.75
  '21':
    type: SHOP
    id: QUARTZ_PILLAR
    buy-price: 12.19
  '22':
    type: SHOP
    id: NETHERRACK
    buy-price: 2.34
    sell-price: 0.94
  '23':
    type: SHOP
    id: NETHER_BRICK
    buy-price: 5.47
  '24':
    type: SHOP
    id: GLOWSTONE
    buy-price: 7.03
    sell-price: 2.5
  '25':
    type: SHOP
    id: SOUL_SAND
    buy-price: 7.06
  '26':
    type: SHOP
    id: END_STONE
    buy-price: 7.03
  '27':
    type: SHOP
    id: SAND
    buy-price: 4.06
  '28':
    type: SHOP
    id: RED_SAND
    buy-price: 3.05
  '29':
    type: SHOP
    id: GRAVEL
    buy-price: 3.52
  '30':
    type: SHOP
    id: OBSIDIAN
    buy-price: 15.0
    sell-price: 5.5
  '31':
    type: SHOP
    id: ICE
    buy-price: 50.0
  '32':
    type: SHOP
    id: PACKED_ICE
    buy-price: 75.0
  '33':
    type: SHOP
    id: SNOW_BLOCK
    buy-price: 250.0
Decoration:
  '0':
    type: SHOP
    id: WHITE_WOOL
    buy-price: 2.34
    sell-price: 1.25
  '1':
    type: SHOP
    id: ORANGE_WOOL
    buy-price: 2.34
    sell-price: 1.25
  '2':
    type: SHOP
    id: MAGENTA_WOOL
    buy-price: 2.34
    sell-price: 1.25
  '3':
    type: SHOP
    id: LIGHT_BLUE_WOOL
    buy-price: 2.34
    sell-price: 1.25
  '4':
    type: SHOP
    id: YELLOW_WOOL
    buy-price: 2.34
    sell-price: 1.25
  '5':
    type: SHOP
    id: LIME_WOOL
    buy-price: 120.0
  '6':
    type: SHOP
    id: PINK_WOOL
    buy-price: 2.34
    sell-price: 1.25
  '7':
    type: SHOP
    id: GRAY_WOOL
    buy-price: 2.34
    sell-price: 1.25
  '8':
    type: SHOP
    id: LIGHT_GRAY_WOOL
    buy-price: 2.34
    sell-price: 1.25
  '9':
    type: SHOP
    id: CYAN_WOOL
    buy-price: 2.34
    sell-price: 1.25
  '10':
    type: SHOP
    id: PURPLE_WOOL
    buy-price: 2.34
    sell-price: 1.25
  '11':
    type: SHOP
    id: BLUE_WOOL
    buy-price: 2.34
    sell-price: 1.25
  '12':
    type: SHOP
    id: BROWN_WOOL
    buy-price: 2.34
    sell-price: 1.25
  '13':
    type: SHOP
    id: GREEN_WOOL
    buy-price: 2.34
    sell-price: 1.25
  '14':
    type: SHOP
    id: RED_WOOL
    buy-price: 2.34
    sell-price: 1.25
  '15':
    type: SHOP
    id: BLACK_WOOL
    buy-price: 2.34
    sell-price: 1.25
  '16':
    type: SHOP
    id: WHITE_STAINED_GLASS
    buy-price: 4.06
  '17':
    type: SHOP
    id: ORANGE_STAINED_GLASS
    buy-price: 4.06
  '18':
    type: SHOP
    id: MAGENTA_STAINED_GLASS
    buy-price: 4.06
  '19':
    type: SHOP
    id: LIGHT_BLUE_STAINED_GLASS
    buy-price: 4.06
  '20':
    type: SHOP
    id: YELLOW_STAINED_GLASS
    buy-price: 4.06
  '21':
    type: SHOP
    id: LIME_STAINED_GLASS
    buy-price: 4.06
  '22':
    type: SHOP
    id: PINK_STAINED_GLASS
    buy-price: 4.06
  '23':
    type: SHOP
    id: GRAY_STAINED_GLASS
    buy-price: 4.06
  '24':
    type: SHOP
    id: LIGHT_GRAY_STAINED_GLASS
    buy-price: 4.06
  '25':
    type: SHOP
    id: CYAN_STAINED_GLASS
    buy-price: 4.06
  '26':
    type: SHOP
    id: PURPLE_STAINED_GLASS
    buy-price: 4.06
  '27':
    type: SHOP
    id: BLUE_STAINED_GLASS
    buy-price: 4.06
  '28':
    type: SHOP
    id: BROWN_STAINED_GLASS
    buy-price: 4.06
  '29':
    type: SHOP
    id: GREEN_STAINED_GLASS
    buy-price: 4.06
  '30':
    type: SHOP
    id: GREEN_STAINED_GLASS
    buy-price: 4.06
  '31':
    type: SHOP
    id: RED_STAINED_GLASS
    buy-price: 4.06
  '32':
    type: SHOP
    id: BLACK_STAINED_GLASS
    buy-price: 4.06
Specialty:
  '0':
    type: SHOP
    id: CHEST
    buy-price: 15.0
  '1':
    type: SHOP
    id: TRAPPED_CHEST
    buy-price: 150.0
  '2':
    type: SHOP
    id: ENDER_CHEST
    buy-price: 6430.0
  '3':
    type: SHOP
    id: ENCHANTING_TABLE
    buy-price: 793.0
  '4':
    type: SHOP
    id: ANVIL
    buy-price: 3543.0
  '5':
    type: SHOP
    id: HOPPER
    buy-price: 22750.0
  '6':
    type: SHOP
    id: OAK_SIGN
    buy-price: 62.5

shops.yml file

**Comment by pablo67340** [comment]
Update 8.1 fixes this issue.
