### ISSUE TITLE
Can't compile from source

### ISSUE THREAD

**Issue by josiahkeeler** [pablo67340/GUIShop#77]
I'm having issues building from source. v 8.0 jar will not work so on 1.16.1 paper, so I decided to build myself. 

`[ERROR] Failed to execute goal on project GUIShop: Could not resolve dependencies for project com.pablo67340.GUIShop:GUIShop:jar:8.0: Could not find artifact space.arim:legacyitemconstructor:jar:0.1.1-SNAPSHOT in spigot-repo (https://hub.spigotmc.org/nexus/content/repositories/snapshots/) -> [Help 1]
[ERROR] `

**Comment by A248** [comment]
Sorry, that was my fault and sadly the change was unavoidable. Change the "arim-repo" repository URL in the pom.xml to this:

```xml
		<repository>
			<id>arim-mvn-lgpl3</id>
			<url>https://mvn-repo.arim.space/lesser-gpl3/</url>
		</repository>
```

Note: This change is already incorporated into #71 but that PR hasn't been merged yet
