### ISSUE TITLE
[meta] Upcoming API change in SilkSpawners v4

### ISSUE THREAD

**Issue by timbru31** [pablo67340/GUIShop#8]
Hi there,

I just wanted to give you a short shoutout about an upcoming API change in SilkSpawners (v4). The update will take some time, but I'll refactor the whole SilkUtil.
I will increase the major version number to v4 since it might (or mostly will) be a breaking change. 
Deprecated methods will be removed, so make sure you update your method here:

https://github.com/pablo67340/GUIShop/blob/e4578d3ff566110e323febff804337fe57b36f7f/src/com/pablo67340/GUIShop/Listeners/PlayerListener.java#L320

Additionally, I recommend to call the `hookIntoSilkSpawners` just once and keep the `SilkUtil` as an instance variable.

**Comment by pablo67340** [comment]
Thank you so much for this timbru. I will look into this change and adjust my plugin accordingly.
