### ISSUE TITLE
after i editing the config i can't click the shop

### ISSUE THREAD

**Issue by bacogi** [pablo67340/GUIShop#81]
[06:14:26 WARN]: [GUIShop] [GUISHOP]: Check the section for shop FarmingDrops in the shops.yml. It was not found.
[06:14:26 ERROR]: Could not pass event InventoryClickEvent to GUIShop v8.1
help me please i can't click the shop ingame

**Comment by Skyslycer** [comment]
So u basicly removed or forgot to add the crops section in the shops.yml. if u wouls provide us with the shops.yml and config.yml it would be really helpful

**Comment by pablo67340** [comment]
When creating a new shop in config.yml, the corresponding shop must also be made in shops.yml, and named the EXACT SAME. This will resolve the issue you are having.
