### ISSUE TITLE
Issue with Selling on 8.4

### ISSUE THREAD

**Issue by Porkason** [pablo67340/GUIShop#83]
The selling doesn't work.

**Comment by Porkason** [comment]
I get this error: https://pastebin.com/3eQRwE7Z

**Comment by Skyslycer** [comment]
As the error says, you were trying to acces it by the console. 
![Screenshot_20210221-015603_Samsung Internet.jpg](https://user-images.githubusercontent.com/73074974/108612338-152fe780-73e8-11eb-81ee-2ef2aa7a8c74.jpg)
But console doesnt have the same attributes as a player, do it throws an exception. That means that sum is wrong.
Either you created like something that runs like shop {playername} in the console when a player clicks sum or you were just trying to acces it in the console. 
I hope that helps.

**Comment by Skyslycer** [comment]
If that fixed it please close the issue, because we would like to keep the issue section clean.

**Comment by pablo67340** [comment]
This command must be sent from a player, and not your console. An extra sender check will be implemented in the next commit.
