### ISSUE TITLE
Exception thrown when config.yml has too many entries

### ISSUE THREAD

**Issue by OortCloud42** [pablo67340/GUIShop#85]
Currently the plugin throws an exception when too many entries are added to config.yml. It tries to add all of them to the fake inventory, causing an ArrayOutOfBounds exception. This can be easily solved by either checking if there's a correct amount of entries in config.yml or simply ignoring excess entries.

**Comment by Skyslycer** [comment]
Yes.

**Comment by pablo67340** [comment]
Valid Issue. I can add additional out of bounds checks to fix this. Optionally, a user can change the rows/columns of the menu to increase the array max size, but keep in mind, the max items a user could use in that case would be 54.

**Comment by pablo67340** [comment]
Fixed as of 9.0.5
