### ISSUE TITLE
item failed to sell and have been returned to your inventory.

### ISSUE THREAD

**Issue by K4mey** [pablo67340/GUIShop#87]
I'm trying to sell an item that's added to the shop and has a sell price such as glow stone but instead i get this error
`failed to sell and have been returned to your inventory.`
does anyone know any fix?

**Comment by Skyslycer** [comment]
Would be really helpfull if you could provide us with more information: Item, Plugin version, shops.yml, config.yml.
Thanks

**Comment by pablo67340** [comment]
This is a very old issue, and the user has not replied. If the user is still using this plugin by now, and still having these issues, they can open another fresh issue and we'll take a look at it.
