### ISSUE TITLE
Users can sell items from shops they don't have access to

### ISSUE THREAD

**Issue by OortCloud42** [pablo67340/GUIShop#88]
I have a few shops configured, and one of them should be accessible only for users in a special group. This works as expected, but users outside of the group can still sell items added only to the shop they don't have access to.

**Comment by Skyslycer** [comment]
As far I looked into the sell code, there is no line of code, if the player has the permission for the item. It could an easy-ish fix, if you could define the permission for specific items too. That would be then stored in the itrm table. The it will just ask if the player has this permission. Could be sum for updates. @pablo67340

**Comment by pablo67340** [comment]
This has been fixed in commit [e9f6cbc](https://github.com/pablo67340/GUIShop/commit/e9f6cbc7d842c5d4807d2a0e95c0d045b51c097e)

Thank you for your report. Please update to GUIShop 8.5 to fix this issue.
