### ISSUE TITLE
Error with /shop or /pshop (i chaned it to this)

### ISSUE THREAD

**Issue by Skyslycer** [pablo67340/GUIShop#89]
https://pastebin.com/m75Gs0Wr
WTF fix your sh*t like it worked fine before. but now it doesnt like whyyy
i mean i reset the config and it still doesnt work and on another server it works tooo wtf

**Comment by pablo67340** [comment]
Closed. Rude af considering I use my spare time to make this plugin FREE. I will fix it when I have the time.
