### ISSUE TITLE
!!!!!!!!!!!!!!Use IntellIj and Gradle rather than NetBeans, Eclipse or VS Code and Maven!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by Amejonah1200** [pablo67340/GUIShop#97]
- Better Auto Completion
- Better Support for Build Tools
- Better Inspections
- Big Community

**Comment by Th3Ph4nt0m** [comment]
Title says everything. Think so too, switch asap!

**Comment by DRSchlaubi** [comment]
First world problems

**Comment by RainbowDashLabs** [comment]
I think we all should use vim.
I just works.

**Comment by Skyslycer** [comment]
Yea, you really gotta switch, like I said!

**Comment by kxmpxtxnt** [comment]
Well, for one thing, what the weird guy says is true, but remember, he's weird.

**Comment by Rich-a-rd** [comment]
Title is what u need.

**Comment by dlsf** [comment]
> I think we all should use vim.
I'm stuck for 3 weeks now, send help

**Comment by pablo67340** [comment]
Someone can easily PR an intellij project file and gradle file if it's really needed that badly.

**Comment by Oribuin** [comment]
How about we all use the build tools we are comfortable with as long as the java code itself isn't garbage who cares.

Just remove any files that aren't required for the plugin to work and relax, if you dont like it, oh well it's the person who maintain's the plugin's issue 
![image](https://user-images.githubusercontent.com/38044508/116587165-1dd5fa00-a912-11eb-8d03-d5faa0f76572.png)
